version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install
        # Current (Jan 2023) AWS image does not contain go
        - yum install golang -y
        - go version
    build:
      commands:
        # TODO: parameterize version
        - wget --no-verbose https://github.com/gohugoio/hugo/releases/download/v0.110.0/hugo_extended_0.110.0_Linux-64bit.tar.gz
        - tar -xf hugo_extended_0.110.0_Linux-64bit.tar.gz hugo
        - mv hugo /usr/bin/hugo
        - rm hugo_extended_0.110.0_Linux-64bit.tar.gz
        - hugo
  artifacts:
    baseDirectory: public
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
